### ISSUE TITLE
"Admission" link is broken

### ISSUE THREAD

**Issue by BanzaiMan** [maninc/fedena#1]
![fedena 2013-08-28 08-31-14](https://f.cloud.github.com/assets/25666/1041880/c327cb40-0fdd-11e3-88ff-c7b1d33c4f4e.png)

After creating an application, the Admission link in the admin menu results in 500 error. Logs show that the template is broken. I am not sure if this is an issue with Fedena in general, or just this fork.

```
Processing StudentController#admission1 (for 127.5.17.129 at 2013-08-28 08:26:27) [GET]
  Parameters: {"action"=>"admission1", "controller"=>"student"}
Rendering template within layouts/application
Rendering student/admission1

ActionView::TemplateError (missing interpolation argument in "%Y-%m-%{count}" ({:object=>"2013-08-28"} given)) on line #66 of app/views/student/admission1.html.erb:
63:         <div class="student_admission_date">
64:           <label for="student_admission_date"><%= t('admission_date') %> <span class="necessary-field">*</span> </label>
65:           <div class="text-input-bg-admission">
66:             <%= calendar_date_select_tag 'student[admission_date]', I18n.l(Date.today,:format=>:default),
67:               :year_range => 15.years.ago..5.years.from_now, :readonly=>true, :popup=>"force" %>
68:           </div>
69:         </div>

    vendor/bundle/ruby/1.8/gems/i18n-0.4.0/lib/i18n/backend/base.rb:177:in `interpolate_without_deprecated_syntax'
    vendor/bundle/ruby/1.8/gems/activerecord-2.3.5/lib/active_record/i18n_interpolation_deprecation.rb:21:in `interpolate'
    vendor/bundle/ruby/1.8/gems/i18n-0.4.0/lib/i18n/backend/base.rb:48:in `translate'
    vendor/bundle/ruby/1.8/gems/i18n-0.4.0/lib/i18n/backend/fallbacks.rb:45:in `translate'
    vendor/bundle/ruby/1.8/gems/i18n-0.4.0/lib/i18n/backend/fallbacks.rb:43:in `each'
    vendor/bundle/ruby/1.8/gems/i18n-0.4.0/lib/i18n/backend/fallbacks.rb:43:in `translate'
    vendor/bundle/ruby/1.8/gems/i18n-0.4.0/lib/i18n.rb:152:in `t'
    vendor/bundle/ruby/1.8/gems/i18n-0.4.0/lib/i18n/backend/base.rb:61:in `localize'
    vendor/bundle/ruby/1.8/gems/i18n-0.4.0/lib/i18n.rb:231:in `l'
    app/views/student/admission1.html.erb:66
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/helpers/form_helper.rb:499:in `fields_for'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/helpers/form_helper.rb:282:in `form_for'
    app/views/student/admission1.html.erb:43
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/renderable.rb:34:in `send'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/renderable.rb:34:in `render'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/base.rb:306:in `with_template'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/renderable.rb:30:in `render'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/template.rb:205:in `render_template'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/base.rb:265:in `render'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/base.rb:348:in `_render_with_layout'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_view/base.rb:262:in `render'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:1250:in `render_for_file'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:945:in `render_without_benchmark'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:51:in `render_without_wicked_pdf'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:51:in `render_without_wicked_pdf'
    app/controllers/application_controller.rb:320:in `render'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:1326:in `default_render'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:1332:in `perform_action_without_filters'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/filters.rb:617:in `call_filters'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/rescue.rb:160:in `perform_action_without_flash'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/flash.rb:146:in `perform_action'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:532:in `send'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:532:in `process_without_filters'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/filters.rb:606:in `process'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:391:in `process'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/base.rb:386:in `call'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/routing/route_set.rb:437:in `call'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:87:in `dispatch'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:121:in `_call'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:130:in `build_middleware_stack'
    vendor/bundle/ruby/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:29:in `call'
    vendor/bundle/ruby/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:29:in `call'
    vendor/bundle/ruby/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
    vendor/bundle/ruby/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:9:in `cache'
    vendor/bundle/ruby/1.8/gems/activerecord-2.3.5/lib/active_record/query_cache.rb:28:in `call'
    vendor/bundle/ruby/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/string_coercion.rb:25:in `call'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/params_parser.rb:15:in `call'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/session/cookie_store.rb:93:in `call'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/failsafe.rb:26:in `call'
    vendor/bundle/ruby/1.8/gems/actionpack-2.3.5/lib/action_controller/dispatcher.rb:106:in `call'
    /usr/share/rubygems/gems/passenger-3.0.21/lib/phusion_passenger/rack/request_handler.rb:97:in `process_request'
    /usr/share/rubygems/gems/passenger-3.0.21/lib/phusion_passenger/abstract_request_handler.rb:521:in `accept_and_process_next_request'
    /usr/share/rubygems/gems/passenger-3.0.21/lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
    /usr/share/rubygems/gems/passenger-3.0.21/lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
    /usr/share/rubygems/gems/passenger-3.0.21/lib/phusion_passenger/classic_rails/application_spawner.rb:99:in `spawn_application'
    /usr/share/rubygems/gems/passenger-3.0.21/lib/phusion_passenger/utils.rb:470:in `safe_fork'
    /usr/share/rubygems/gems/passenger-3.0.21/lib/phusion_passenger/classic_rails/application_spawner.rb:84:in `spawn_application'
    /usr/share/rubygems/gems/passenger-3.0.21/lib/phusion_passenger/spawn_manager.rb:230:in `spawn_rails_application'
    /usr/share/rubygems/gems/passenger-3.0.21/lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
    /usr/share/rubygems/gems/passenger-3.0.21/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
    /usr/share/rubygems/gems/passenger-3.0.21/lib/phusion_passenger/abstract_server.rb:357:in `__send__'
    /usr/share/rubygems/gems/passenger-3.0.21/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
    /usr/share/rubygems/gems/passenger-3.0.21/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
    /usr/share/rubygems/gems/passenger-3.0.21/helper-scripts/passenger-spawn-server:102

Rendering /var/lib/openshift/521de8635973ca53ce000274/app-root/runtime/repo/public/500.html (500 Internal Server Error)
```

**Comment by teedechventures** [comment]
Hi,please how did you solve the admission link issue. I have the same problem. thanks

**Comment by ngethe** [comment]
Was this solved? have the same issue

**Comment by teedechventures** [comment]
No it wasn't solved..i was able to get it to work perfectly on windows but
couldn't get it to work perfectly on openshift cloudbecause of the broken
link. Currently reworking a version u might be able to host on amazon aws.

**Comment by ngethe** [comment]
keep me posted on this amazon dev

**Comment by teedechventures** [comment]
ok pal

**Comment by maninc** [comment]
Fixed this I18n issue and other similar issues. Let me know if I had missed any.
